repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    args: [--line-length=79, --safe]
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
    name: flake8 except __init__.py
    args: [--exclude=__init__.py]
    language_version: python3
  - id: flake8
    name: flake8 only __init__.py
    args: [--ignore=E501 F401]  # ignore imported unused in __init__.py
    files: __init__.py
    language_version: python3
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.3.0
  hooks:
  - id: seed-isort-config
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3
