version: '3.7'

services:
  db:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/data/:/var/lib/postgresql/data
      - .db/socket/:/var/run/postgresql/
  rabbitmq:
    image: rabbitmq:3-management
  cidbservice:
    build: .
    environment:
      POSTGRES_USER: odoo
      POSTGRES_GROUP: odoo
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 54320
      GUNICORN_WORKERS: 1
      GUNICORN_TIMEOUT: 3600
    volumes:
      - ./cidbservice.conf:/etc/cidbservice.conf
      - .db/socket/:/var/run/postgresql/
      - ./:/workspace
    depends_on:
      - db
      - rabbitmq
    labels:
      docky.main.service: true
      docky.user: dbservice
      traefik.backend: cidbservice
      traefik.frontend.rule: "Host:ci.dy"
      traefik.port: 54320
