version: '3.7'

services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - .db/data/:/var/lib/postgresql/data
      - .db/socket/:/var/run/postgresql/
  rabbitmq:
    image: rabbitmq:3-management
  cidbservice:
    build: .
    environment:
      POSTGRES_USER: postgres
      GUNICORN_WORKERS: 1
      GUNICORN_TIMEOUT: 3600
    volumes:
      - ./config/:/etc/dbservice/
      - .db/socket/:/var/run/postgresql/
      - ./:/cidbservice
    depends_on:
      - db
      - rabbitmq
    labels:
      docky.main.service: true
      traefik.frontend.rule: "Host:ci.dy"
      traefik.port: 54320
    entrypoint: /usr/local/bin/dev-entrypoint
