version: '2'

services:
  cidbservice:
    build: .
    entrypoint: /usr/local/bin/docker-cidbservice.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_GROUP: postgres
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 54320
    volumes:
      - ./cidbservice.conf:/etc/cidbservice.conf
      - /var/run/postgresql/:/var/run/postgresql/
    ports:
      - "54320:54320"
    restart: always
    links:
      - rabbitmq
  celery:
    build: .
    entrypoint: /usr/local/bin/docker-celery.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_GROUP: postgres
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 54320
    volumes:
      - ./cidbservice.conf:/etc/cidbservice.conf
      - /var/run/postgresql/:/var/run/postgresql/
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    restart: always
